### ISSUE TITLE
No docker image in manifest list in new linux and mac versions

### ISSUE THREAD

**Issue by ankit2001** [blabla1337/skf-flask#736]
docker compose up is giving me this error for pulling mysql image.

<img width="543" alt="Screenshot 2021-03-14 at 12 20 58 PM" src="https://user-images.githubusercontent.com/44541855/111060229-47050d00-84c1-11eb-866a-daab20c941e7.png">

**Comment by blabla1337** [comment]
Fixed in #737

**Comment by BenoitSerrano** [comment]
Hey! Still having this issue:
``` 
> skf-flask git:(main) docker-compose up
Pulling mysql (blabla1337/mysql:)...
latest: Pulling from blabla1337/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

while on the most recent commit:
```
commit 040eaf29f220b59b4b9a52a73b61332fb99a23ad (HEAD -> main, origin/main, origin/HEAD)
Merge: 5916a6404 596d28c83
Author: Glenn ten Cate <glenn.ten.cate@owasp.org>
Date:   Thu Mar 17 09:20:46 2022 +0100

    Merge pull request #753 from MeVitae/k8s-dabase-update

    Add persistent storage to mysql database in K8s and a volume in docker-compose
```

Anything I did wrong?

**Comment by blabla1337** [comment]
Hmm interesting, I'm also using a Mac but don't have this error
Also it seems it tries the linux/arm64/v8? What type of Mac do you have?

Currently the Mysql image is only supporting 
armv7 
amd64

https://hub.docker.com/repository/registry-1.docker.io/blabla1337/mysql/tags?page=1&ordering=last_updated
